### ISSUE TITLE
[Hub] Dashboard UI is having issues with the charts

### ISSUE THREAD

**Issue by poppabear8883** [getcandy/getcandy#100]
When you first load the dashboard the `Sale Performance` chart is bugged. Simply resizing the window seems to cause it to fix itself ?

![chrome_3B7jCKbv8O](https://user-images.githubusercontent.com/7263458/151368498-a60dc0e1-9b82-412e-84bf-f5b588fed3cf.png)

https://user-images.githubusercontent.com/7263458/151368568-cde0d3aa-cd20-4d16-926c-dee533a28d67.mp4

![ApplicationFrameHost_wL2P8HvGSo](https://user-images.githubusercontent.com/7263458/151368845-986d49d5-0bcb-4ca0-bbc9-3aade1bcf693.png)

**Comment by glennjacobs** [comment]
Fixed in upcoming release.
