### ISSUE TITLE
[Hub]: Collections product search feature is not reliable 

### ISSUE THREAD

**Issue by poppabear8883** [getcandy/getcandy#114]
The search as shown below doesn't seem to work as expected.

I expect to be able to search by attribute "name" for example & by sku.

Debounce feels like it could be adjusted a little lower as well.

![chrome_1V8zKwrp2Z](https://user-images.githubusercontent.com/7263458/151663453-c69753fe-6c77-4c47-9f05-161d2182cd25.png)

https://user-images.githubusercontent.com/7263458/151663462-28a0085c-f397-4804-a193-964da23053ac.mp4

**Comment by alecritson** [comment]
Which scout driver are you using? If it's the MySQL one, it's very limiting and more of a "get up and running" driver before you decide on what you'll be replacing it with.

**Comment by poppabear8883** [comment]
I'm using Meilisearch

**Comment by alecritson** [comment]
I've tried this on my local set up with Meilisearch and I haven't really noticed anything wrong with the search. Have you had a look at the index to see what's in there? Maybe that will shed some light on what's happening.

**Comment by poppabear8883** [comment]
Closing this. I have not had this issue since I have rebuilt my Docker (Sail) container.
