### ISSUE TITLE
[Suggestion]: Add products to collection based on conditions

### ISSUE THREAD

**Issue by poppabear8883** [getcandy/getcandy#115]
Here is an example as to how Shopify does theirs.

![image](https://user-images.githubusercontent.com/7263458/151664048-11ecfc5c-a9ba-4c5a-8bbd-ae23a3107a38.png)

![image](https://user-images.githubusercontent.com/7263458/151664072-4dff30a2-4107-485a-80ae-edcc049b5506.png)

![image](https://user-images.githubusercontent.com/7263458/151664093-a0c80f9a-9496-4539-8874-569ec0c8d450.png)

**Comment by alecritson** [comment]
Dynamic collections are absolutely something we will be covering in an upcoming release 😊

**Comment by glennjacobs** [comment]
Closing this issue, as dynamic collections are already on our roadmap.
