### ISSUE TITLE
Make hub views publishable

### ISSUE THREAD

**Issue by zhmyh** [getcandy/getcandy#128]
As Developer, I want more control over admin hub, for example, I want add bulk delete, but don't have access to admin hub resources

**Comment by glennjacobs** [comment]
We won't be making admin hub views publishable, as it will cause a terrible maintenance concern. 

Instead, we will be introducing features you can extend to add functionality at specific points.

**Comment by jishadp** [comment]
So Please tell me, If I need to change the add product form elements or change menu items, What I can do for that ?

**Comment by glennjacobs** [comment]
At the moment you can modify the side menu, so you can add new links to your new screens. See https://github.com/getcandy/getcandy/blob/main/packages/admin/src/Menu/SidebarMenu.php

We will be introducing more menus you can tap into over time.
