### ISSUE TITLE
Error registering tax drivers

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#129]
The method for registering tax drivers in the docs doesn't work: https://docs.getcandy.io/getcandy/taxation.html#extending

You get the error "Non-static method Illuminate\Support\Manager::extend() cannot be called statically

**Comment by alecritson** [comment]
Thanks @ryanmitchell I'm going to be taking a look at this one this morning so should hopefully have a PR for it up with doc fixes soon.
