### ISSUE TITLE
Bug[Hub]: Issue with description attribute/field default value

### ISSUE THREAD

**Issue by poppabear8883** [getcandy/getcandy#130]
For this example I will use `Collections` as the parent of the attributes, however this will apply to them all.

When #124 was merged the `Description` attribute became optional.

The issue I am noticing is that when you create a new collection and then: 
```php
$collection->translateAttribute('description');
```
you will get a return value of `null`

Then you go into the hub and you `Edit ` said collection, then simply click the `Save` button. 
*DO NOT TYPE IN THE DESCRIPTION FIELD, JUST SIMPLY SAVE*

then check:
```php
$collection->translateAttribute('description');
```

you will get `{"en":null}`:

```json
"description":{"field_type":"GetCandy\\FieldTypes\\TranslatedText","value":{"en":null}}
```
and because of this:
```php
/**
         * If we don't return a field type, then somethings up and it doesn't look like
         * this is translatable, in this case, just return what the fields value is.
         */
        if (! $value instanceof FieldType) {
            return $field->getValue();
        }
```

it will return the string literal `{"en":null}`

Then go back into the same collection to edit the field.
This time type something into the description field, 
*THEN DELETE EVERYTHING FROM THE FIELD EFFECTIVELY MAKING IT EMPTY AGAIN*
and click `Save` and check the data again:

```php
$collection->translateAttribute('description');
```

You will this time get an `empty string`.
This is whats expected even if you don't trigger the 2 way binding of the field to update the `attribute_data property` in Livewire.

```json
"description":{"field_type":"GetCandy\\FieldTypes\\TranslatedText","value":{"en":""}}
```

**Comment by alecritson** [comment]
Thanks @poppabear8883 should be able to get a PR up soon :)
