### ISSUE TITLE
Third party route binding can cause conflicts in the hub

### ISSUE THREAD

**Issue by alecritson** [getcandy/getcandy#132]
There's been an instance of at least one package registering their own route binding in their service providers. This has led to an issue where GetCandy's own route bindings in the hub will throw 404 errors.

For example, we have this route:

```php
Route::get('/collections/{collection}', CollectionShow::class)->name('hub.collections.show');
```

Which uses route model binding to resolve the collection in the Livewire component.

Statamic CMS implements their own route binding in their service provider [as seen here](https://github.com/statamic/cms/blob/d29863a65da7d22b20a92004835ec48c87fc4e19/src/Providers/RouteServiceProvider.php#L45)

```php
Route::bind('collection', function ($handle) {
    throw_unless(
        $collection = Collection::findByHandle($handle),
        new NotFoundHttpException("Collection [$handle] not found.")
    );

    return $collection;
});
```

This causes all GetCandy routes which bind `{collection}` to fail and throw a 404.

To help solve this, we could implement our own route binding, but prefix, something like:

```php
Route::bind('gc_collection', function ($id) {
    throw_unless(
        $collection = Collection::find($id),
        new NotFoundHttpException()
    );

    return $collection;
});

Route::get('/collections/{gc_collection}', CollectionShow::class)->name('hub.collections.show');
```

The syntax is just an example, not sure if snake case would work, but going forward, this would mean that we wouldn't have to rely on third-party packages not conflicting with Getcandy.

**Comment by ryanmitchell** [comment]
Just by way of update on this I've got a PR open on Statamic to resolve this on their side: https://github.com/statamic/cms/pull/5775

I actually don't feel like you're doing anything wrong as you aren't binding variables to the routes (from what I can see) in the same way, but using implicit binding which is a reasonable approach.

**Comment by alecritson** [comment]
Closing this as it looks like it's been solved Statamic's side and there's not anything for us to do.
