### ISSUE TITLE
Variant fails to save when choosing an existing image.

### ISSUE THREAD

**Issue by daikazu** [getcandy/getcandy#147]
If you `Choose Existing` when updating the image on a product variant you receive the following error when trying to save.

<img width="360" alt="CleanShot 2022-02-09 at 02 00 55@2x" src="https://user-images.githubusercontent.com/4039367/153139090-79ee69c2-bf01-43ce-b014-d2fd7817e7a8.png">

Once you click `Remove` you are able to save again

**Comment by alecritson** [comment]
Thanks @daikazu there's now a PR for the fix https://github.com/getcandy/getcandy/pull/155
