### ISSUE TITLE
Admin Hub CSS issues

### ISSUE THREAD

**Issue by KKSzymanowski** [getcandy/getcandy#156]
The compiled [`app.css` ](https://github.com/getcandy/getcandy/blob/7b0daaa6f3a7f5df32e2395b7bdbe6bbd9d4be5f/packages/admin/public/app.css) file for Admin Hub doesn't seem to include some classes (eg. `sm:justify-between`) used by Laravel's Tailwind pagination. 
These classes may have been pruned from the compiled file because Tailwind didn't see them used anywhere.

The CSS file may be outdated because recompiling it fixes the pagination links layout.

I believe instead of simply recompiling it GetCandy should use it own pagination template. The default Tailwind pagination in Laravel has changed a handful of times since it was added and different projects may use different versions of the Laravel 8 release. Because of this it may be impossible to make the pagination links look consistent regardless of the specific Laravel minor release if we were to continue using the default template file.

What do you think?

**Comment by KKSzymanowski** [comment]
Below is an example of layout issues I'm talking about.

Before recompilation:
![image](https://user-images.githubusercontent.com/13980973/153267863-e8d7db9e-c8ed-4ee2-905c-5a1e0552b78e.png)

After recompilation:
![image](https://user-images.githubusercontent.com/13980973/153267887-f021b590-6ea8-4d9a-bf58-7e298d941267.png)

**Comment by alecritson** [comment]
I think we did explore using our own but couldn't see an easy way to set the template without having to specify it every time and without affecting the dev's actual Laravel install.

**Comment by markmead** [comment]
This should be fixed with #334 🤞
