### ISSUE TITLE
Extending taxes

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#164]
I've just updated to beta9 but am unfortunately still having issues with extending taxes.

I add:

```
        \GetCandy\Facades\Taxes::extend('avatax', function ($app) {
            return $app->make(Drivers\AvataxDriver::class);
        });
```

to my AppServiceProvider register() method.

And I get an error:

```
Illuminate\Contracts\Container\BindingResolutionException
Target [GetCandy\Base\TaxManagerInterface] is not instantiable.
```

I can get around the error by binding the interface before extend the facade:

```
        $this->app->bind(\GetCandy\Base\TaxManagerInterface::class, function ($app) {
            return $app->make(\GetCandy\Managers\TaxManager::class);
        });
```

However, the error is then that `Driver [avatax] not supported.`.

I've verified the driver is registered by calling `\GetCandy\Facades\Taxes::driver('avatar')` and I do get the class I registered, but it seems to be lost by the time the cart calculations happen.

I've tried investigating this further but dont seem to be able to find the reason why its not working as expected.

**Comment by alecritson** [comment]
@ryanmitchell Thanks for reporting.

Try putting the `extend` call in the `boot` method rather than `register`. It's likely the docs will need an update to reflect this.

Here's what I found, which is an excerpt from Taylor's book apparently:

> A common mistake when using service providers is attempting to use the services provided by another provider in the register method. Since, within the register method, we have no guarantee all other providers have been loaded, the service you are trying to use may not be available yet. So, service provider code that uses other services should always live in the boot method. The register method should only be used for, you guessed it, registering services with the container. Within the boot method, you may do whatever you like: register event listeners, include a routes file, register filters, or anything else you can imagine

**Comment by ryanmitchell** [comment]
I tried that too and it didn't work either. The Taxes::extend callable never gets called...

**Comment by ryanmitchell** [comment]
Yep thats it now thanks! 😄  

You should also update the docs as the custom driver getBreakdown() method should return a Collection instance not an int.

**Comment by alecritson** [comment]
Glad it worked I'll try and get that merged asap. There is a new PR for some tweaks to docs that target the tax extending bits, so hopefully should be clearer once that's up!
