### ISSUE TITLE
Cartline Modifiers

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#166]
We have a specific price for some users that we want to sell items at and for a number of reasons they cant be built into the pricing table, so we have meta on the cart line that we use to determine the `unitPrice`. I'm using a cart line modifier to amend the price on `calculating()` which I thought would take effect, but it gets overwritten by the logic in `GetCandy\Actions\Carts\CalculateLine`. I know I can override the price by switching to `calculated()` but that then means we lose the tax calculations etc and need to repeat a lot of functionality in `CalculateLine::execute()` which doesn't feel right.

So my question is how would you feel about `CalculateLine::execute()` being updated to check for the presence of a unitPrice that may have already been added by a cart line modifier, and using it as the base of its calculations if available? I can PR it if you are happy.

**Comment by alecritson** [comment]
Sounds like it could be useful, happy to start a draft PR with the idea then take it from there if it's easy enough to do?

**Comment by ryanmitchell** [comment]
Yep I’ll work on it tomorrow
