### ISSUE TITLE
Certificate  Expired

### ISSUE THREAD

**Issue by Elshaden** [getcandy/getcandy#17]
When Running
 php artisan getcandy:install

I Get 
  cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cdn.getcandy.io/data/countries+states.json

**Comment by glennjacobs** [comment]
I can't replicate this. If you open the link in a browser, do you see the same?

**Comment by sunel** [comment]
@Elshaden 

Th problem is with your local certificate

Download cacert.pem from here https://curl.se/docs/caextract.html

in your php.ini add it as below 

```
[curl]
curl.cainfo="path\to\certs\cacert.pem"

[openssl]
openssl.cafile="path\to\certs\cacert.pem"
```

Restart and check

**Comment by glennjacobs** [comment]
@sunel I did think this too. However, the fact it was showing as expired and not invalid confused me.

**Comment by glennjacobs** [comment]
Closing as the SSL certificate is valid and not expired.
