### ISSUE TITLE
Product Activity - Alec Ritson

### ISSUE THREAD

**Issue by olimortimer** [getcandy/getcandy#18]
The activity log at the bottom of a product shows 'Alec Ritson' as the staff member who made the changes, rather than the actual staff member.

**Comment by glennjacobs** [comment]
Thanks, we'll get this sorted in the next release.

**Comment by alecritson** [comment]
We've just pushed out `2.0-beta5` for the admin hub.

This release comes with a few changes, but the most impactful is that we've moved to a monorepo on this repository and the dependency you use has changed.

To get this update you simply need to make a change in your composer file.

From 

```js
"getcandy/getcandy": "^2.0"
```

To

```js
"getcandy/admin": "^2.0"
```

And then run `composer update`. In the event that packagist hasn't indexed the update core you may need to run this with the `--with-dependencies` argument.

Once updated, if you still find this issue persists, feel free to re open and we can take a look :)
