### ISSUE TITLE
Upon user login old cart with existing order is loaded

### ISSUE THREAD

**Issue by przper** [getcandy/getcandy#186]
- GetCandy version: 2.0-beta9 
- Laravel Version: v8.83.0
- PHP Version: 8.1.2
- Database Driver & Version: mysql

### Expected Behaviour:
User add items to cart. Order is created from the cart. 

    public function order()
    {
        $this->cart->getManager()->createOrder();
        $order = $this->cart->order;

        CartSession::forget();

        return redirect(route('order.payment', $order));
    }

User now has no cart active. It will be created when needed with "CartSession::add(...)".
User now logouts and logins. **No new cart or an empty one** will be assigned by Getcandy\Listeners\CartSessionAuthListener

### Actual Behaviour:

Getcandy\Listeners\CartSessionAuthListener upon login loads the last user cart regardless if it was consumed or not

Getcandy\Listeners\CartSessionAuthListener

    public function login(Login $event)
    {
        $currentCart = CartSession::current();

        if ($currentCart && !$currentCart->user_id) {
            CartSession::associate(
                $currentCart,
                $event->user,
                config('getcandy.cart.auth_policy')
            );
        }

        if (!$currentCart) {
            // Does this user have a cart?
            $userCart = Cart::whereUserId($event->user->getKey())->latest()->first();

            if ($userCart) {
                CartSession::use($userCart);
            }
        }
    }

User has cart with old items. In my CartPage blade template I use

    <button
        wire:click="order"
        @if($cart->lines->isEmpty() || !$cart->getManager()->canCreateOrder())
            disabled
        @endif
    >
        Make Order
    </button>

The "!$cart->getManager()->canCreateOrder" part throws OrderExistsException.php

Is this expected behavior? What should be done with current cart after creating an order from it?

### Steps To Reproduce:

Add items to cart. Make order from cart. Logout. Login. Go to CartPage. Get Exception

**Comment by alecritson** [comment]
Hi @przper 

Thanks for reporting this. We'll take a look at this as soon as we can, looks like we need to be adding a check if the cart already had an order and offering up a new one.

From looking at your code above I would say you should be using the cart during the checkout process and then once payment is taken, create the order and update the fields. This stops you from having a lot of unfinished orders in the database and creating noise.
