### ISSUE TITLE
Products - Default values shown

### ISSUE THREAD

**Issue by olimortimer** [getcandy/getcandy#19]
- Actual Product SKU not shown
- Stock shows 250, although products have less stock set against them
- Against Variants, it shows 'STOCK (INCOMING) - 15 (5)' against all variants, no matter what stock is set against them

**Comment by glennjacobs** [comment]
Thanks, we'll look into this.

**Comment by alecritson** [comment]
We've just pushed out `2.0-beta5` for the admin hub which should address this issue.

This release comes with a few changes, but the most impactful is that we've moved to a monorepo on this repository and the dependency you use has changed.

To get this update you simply need to make a change in your composer file.

From 

```js
"getcandy/getcandy": "^2.0"
```

To

```js
"getcandy/admin": "^2.0"
```

And then run `composer update`. In the event that packagist hasn't indexed the update core you may need to run this with the `--with-dependencies` argument.

Once updated, if you still find this issue persists, feel free to re open and we can take a look :)
