### ISSUE TITLE
Products list empty after create new language and set it as default

### ISSUE THREAD

**Issue by scramatte** [getcandy/getcandy#193]
- GetCandy version:  2.0 beta
- Laravel Version: 8.75
- PHP Version: 8.0.10
- Database Driver & Version: Percona Server 5.7 (Mysql) 

### Expected Behaviour:
List the products

### Actual Behaviour:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/188766/155736823-c9516ed4-2029-4b58-b0e0-db06223f4114.png">

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/188766/155736952-35ed2e78-8a4f-4d8b-b294-739e3c9b3c96.png">

### Steps To Reproduce:
Add a new language and set it as default

**Comment by alecritson** [comment]
It looks like you need to reimport via scout when you switch them over. Currently there's no automatic way for this in GetCandy so it would be a case of manually running:

```sh
php artisan scout:import GetCandy\\Models\\Product
```

We may look at this again in the future to see what can be done. Will close for now until it's revisited.
