### ISSUE TITLE
display an order from hub throw exception

### ISSUE THREAD

**Issue by scramatte** [getcandy/getcandy#196]
- GetCandy version:  2.0 beta
- Laravel Version: 8.75
- PHP Version: 8.0.10
- Database Driver & Version: Percona Server 5.7 (Mysql) 

### Expected Behaviour:
Just view an order from hub

### Actual Behaviour:
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/188766/155742355-ad089851-3223-4223-b757-a6a32c1c2bb8.png">

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/188766/155742418-ae9741e2-05f1-4297-a1a3-991f021d45f1.png">

### Steps To Reproduce:
Place an order on frontend and try to display it on hub

**Comment by alecritson** [comment]
We've got some big updates coming to these pages which will hopefully resolve these issues.

**Comment by glennjacobs** [comment]
I checked this, and it seems the demo store is storing tax breakdowns with a `description` attribute, rather than `name` which is what the admin hub is expecting. 

Not sure if the admin hub or the demo store is wrong. But we need to fix it up one way or the other.
