### ISSUE TITLE
Change default Locale throw exceptions on hub...

### ISSUE THREAD

**Issue by scramatte** [getcandy/getcandy#197]
- GetCandy version:  2.0 beta
- Laravel Version: 8.75
- PHP Version: 8.0.10
- Database Driver & Version: Percona Server 5.7 (Mysql) 

### Expected Behaviour:
Be able to display products page with another locale than "en"

### Actual Behaviour:
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/188766/155765319-a9285a6d-f177-4e47-a5aa-6c2dfb751acb.png">

### Steps To Reproduce:
create a new lang resource  and change locale  into config/app.php

**Comment by alecritson** [comment]
I think this is related to #193 closing this one in favour of the response over there.
