### ISSUE TITLE
staff guard not found

### ISSUE THREAD

**Issue by IgorDePaula** [getcandy/getcandy#20]
I follow all steps dy docs, but I access the hub, I got:

![Captura de tela de 2021-12-30 14-44-31](https://user-images.githubusercontent.com/2833993/147775865-85380e2f-3608-46ff-a8a8-3f49b04a2e32.png)

I using, laravel 8.7, laravel sail 8.1, php 8.1

**Comment by glennjacobs** [comment]
Did you update your auth.php config with

```

'guards' => [
    // ...
    'staff' => [
        'driver' => 'getcandyhub',
    ],
]

```

?

**Comment by IgorDePaula** [comment]
Resolved

**Comment by alecritson** [comment]
We've just pushed out `2.0-beta5` for the admin hub which should address this issue, you no longer need to specify this in your config.

This release comes with a few changes, but the most impactful is that we've moved to a monorepo on this repository and the dependency you use has changed.

To get this update you simply need to make a change in your composer file.

From 

```js
"getcandy/getcandy": "^2.0"
```

To

```js
"getcandy/admin": "^2.0"
```

And then run `composer update`. In the event that packagist hasn't indexed the update core you may need to run this with the `--with-dependencies` argument.

Once updated, if you still find this issue persists, feel free to re open and we can take a look :)
