### ISSUE TITLE
Under construction?

### ISSUE THREAD

**Issue by IgorDePaula** [getcandy/getcandy#21]
![Captura de tela de 2021-12-30 18-40-12](https://user-images.githubusercontent.com/2833993/147789991-b1e642bd-65ee-4b18-8c60-06d285350b79.png)
 I don't understand, this is stable?

**Comment by glennjacobs** [comment]
GetCandy 2 is currently in public beta. This is explained in the installation documentation. 

Some of the outstanding hub functionality will be released later in Jan 2022.

**Comment by IgorDePaula** [comment]
Ok, now I understand.

**Comment by IgorDePaula** [comment]
And not, the docs not mentioned beta.

**Comment by glennjacobs** [comment]
![image](https://user-images.githubusercontent.com/647407/147832521-23778cf8-84b8-4b46-b76d-176c84de57da.png)

**Comment by IgorDePaula** [comment]
Sorry, I look into page with control F, inclusive, but not found.

**Comment by alecritson** [comment]
We've just pushed out `2.0-beta5` for the admin hub, this should have some initial screens for customers.

This release comes with a few changes, but the most impactful is that we've moved to a monorepo on this repository and the dependency you use has changed.

To get this update you simply need to make a change in your composer file.

From 

```js
"getcandy/getcandy": "^2.0"
```

To

```js
"getcandy/admin": "^2.0"
```

And then run `composer update`. In the event that packagist hasn't indexed the update core you may need to run this with the `--with-dependencies` argument.
