### ISSUE TITLE
Algolia like dependency

### ISSUE THREAD

**Issue by IgorDePaula** [getcandy/getcandy#22]
If Algolia is required, can put as dependency?

![Captura de tela de 2021-12-30 18-44-21](https://user-images.githubusercontent.com/2833993/147790051-1acbf3fd-37fe-4531-b0bc-8afad83e5799.png)

**Comment by glennjacobs** [comment]
GetCandy does not require Algolia. If you wish to use Algolia as your search driver, we suggest you follow the Laravel Scout documentation.

**Comment by IgorDePaula** [comment]
I install like docs, I not install algolia.

**Comment by IgorDePaula** [comment]
Like print, your lib require algolia, not me.

**Comment by glennjacobs** [comment]
The docs are VuePress. You can follow their instructions. 

It's not something we'll be supporting here.

**Comment by IgorDePaula** [comment]
What?

**Comment by glennjacobs** [comment]
> What?

Sorry, getting confused here.

Seems you have not configured Laravel Scout to use either MySQL or Meilisearch as per the installation instructions. Laravel Scout uses Agolia as its default search engine. We not tested Algolia, but it should work. 

See https://laravel.com/docs/8.x/scout#algolia

and https://docs.getcandy.io/installation.html#search-configuration

**Comment by IgorDePaula** [comment]
Ok, I thinked was optional.

**Comment by glennjacobs** [comment]
> Ok, I thinked was optional.

Thanks for the feedback. I'll look to update the docs to make it more obvious.
