### ISSUE TITLE
quiljs is down and it's slowing down the hub

### ISSUE THREAD

**Issue by Xoshbin** [getcandy/getcandy#225]
- GetCandy version: 2.0-beta10.1
- Laravel Version: 9
- PHP Version: 8.1
- Database Driver & Version: MySql

### Expected Behaviour:
To load the hub in a second

### Actual Behaviour:
It takes three minutes to load the hub

Hi, https://cdn.quilljs.com/1.3.6/quill.snow.css is not working and it's slowing down the hub to three minutes not showing anything
And that's very boring, you have to wait three minutes every time you visit another page in the hub!!!
and their website is down too, It's been a week been like that.
https://quilljs.com/

**Comment by alecritson** [comment]
@Xoshbin The two links you provided load without any issues. 

https://downforeveryoneorjustme.com/quilljs.com?proto=https

Closing as I don't think there is a problem with the CDN.

**Comment by Xoshbin** [comment]
@alecritson @glennjacobs 
<img width="1376" alt="Screen Shot 2022-03-14 at 11 22 21 AM" src="https://user-images.githubusercontent.com/1606070/158132718-861526bb-6a51-4050-861f-e2f54f23e8d1.png">

**Comment by glennjacobs** [comment]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/647407/158133073-9435fd55-a182-49bf-8a79-fbc1cafb7869.png">

???

Where are you located @Xoshbin ? Could it be a location-based block?

**Comment by Xoshbin** [comment]
It looks like it's kinda playing, that second I opened the link it was down, and now it's green, I'm located in Kurdistan, Iraq. I don't believe it's a location issue because right now the website is working too. You have to consider this website if it's going down and up again.

**Comment by glennjacobs** [comment]
We will move assets like this into the system at some point. They're just using CDNs for the moment whilst we're in beta.
