### ISSUE TITLE
Toggle buttons not working in the admin hub

### ISSUE THREAD

**Issue by Xoshbin** [getcandy/getcandy#226]
- GetCandy version: 2.0-beta10.1
- Laravel Version: 9
- PHP Version: 8.1
- Database Driver & Version: MySql

None of the toggle buttons is working in the admin hub!!

**Comment by alecritson** [comment]
Hi @Xoshbin I've loaded up two instances of the hub and toggles appear to be working fine. Could this be related to the CDN issue you're having? 

Closing this for now unless steps to reproduce can be given.

**Comment by glennjacobs** [comment]
Yep, work fine for me also.

**Comment by Xoshbin** [comment]
Yes it was related to the CDN, Now it's working. Thank you
