### ISSUE TITLE
Unable to retrieve URL morphTo element relationship

### ISSUE THREAD

**Issue by Xenovalis** [getcandy/getcandy#24]
I'm not able to get products from the URL slug, I believe that this line
https://github.com/getcandy/core/blob/5f11411655869cc9fb5e78b9b42f755f4b814ae6/src/Models/Url.php#L45
would need to be `element` instead of `elements`
```php
// With public function elements()
$url->element // returns null
$url->elements // returns null

// With public function element()

$url->element // returns Product or Collection
```

**Comment by glennjacobs** [comment]
Looks like that's an issue, we'll look into that tomorrow.

In the meantime, you could look to load via the Product model. See https://laravel.com/docs/8.x/eloquent-relationships#querying-morph-to-relationships

**Comment by alecritson** [comment]
This has been updated on the core and scheduled for the next beta release :) Will post here once it's ready to go!

**Comment by alecritson** [comment]
We've just pushed out `2.0-beta5` for the admin hub.

This release comes with a few changes, but the most impactful is that we've moved to a monorepo on this repository and the dependency you use has changed.

To get this update you simply need to make a change in your composer file.

From 

```js
"getcandy/getcandy": "^2.0"
```

To

```js
"getcandy/admin": "^2.0"
```

And then run `composer update`. In the event that packagist hasn't indexed the update core you may need to run this with the `--with-dependencies` argument.

Once updated, if you still find this issue persists, feel free to re open and we can take a look :)
