### ISSUE TITLE
Currency exchange rate should not be limited by 255

### ISSUE THREAD

**Issue by armezit** [getcandy/getcandy#249]
- GetCandy version: 2.0-beta10
- Laravel Version: 9.3.1
- PHP Version: 8.1.2
- Database Driver & Version:

### Expected Behaviour:

Currency exchange rate should not be limited by 255. Many exchange rates are much more than this value.
For example, IRR/USD exchage rate is about 250000.

### Actual Behaviour:

Upper limit of currency exchange rate is 255.

### Steps To Reproduce:

Try to define a new currency in Hub with an exchange rate larger than 255.

**Comment by alecritson** [comment]
This should be patched on `v2.0-beta12`
