### ISSUE TITLE
When you plan add other field types from docs?

### ISSUE THREAD

**Issue by devmansurov** [getcandy/getcandy#25]
In candy docs you have this field types:

```
GetCandy\FieldTypes\Color	
GetCandy\FieldTypes\Datetime	
GetCandy\FieldTypes\File	
GetCandy\FieldTypes\JSON	
GetCandy\FieldTypes\Measurement	
GetCandy\FieldTypes\Reference	
GetCandy\FieldTypes\Select	
GetCandy\FieldTypes\Toggle	
GetCandy\FieldTypes\URL
```

I tried create cake store with you package. 

**Problem 1**

Cake's has multiple decorations with separate multiple images and custom price for gm or kg

**Problem 2**

Each cake has own multiple fillings with images and custom price for gm or kg. This fillings can be multiselect. User can order cake with custom fillings. Also, they can be interconnected with each other so that the client cannot order the filling of the cake without other related fillings that the chosen filling needs.

How I can solve this problem with `getcandy` ?

**Comment by glennjacobs** [comment]
Field types - good spot, we neglected to say which were "coming soon...". I'll get the docs updated, but you should expect the additional types to be added over the coming couple of months whilst we're still in beta.

Cakes - sounds like a configurable product, which we don't currently have an addon for. So you could try use the meta data on Cart Lines, product variant attributes for additional information and of course the variant options. Failing that, you may need to make your own custom addon to suit your needs, storing the information in the meta field as mentioned.

**Comment by glennjacobs** [comment]
I've removed those field types from the docs for the moment, so as not to confuse.
