### ISSUE TITLE
HasTranslations::translate() method ignores $locale parameter 

### ISSUE THREAD

**Issue by armezit** [getcandy/getcandy#251]
- GetCandy version: 2.0-beta10
- Laravel Version: 9.3.1
- PHP Version: 8.1.2
- Database Driver & Version:

### Expected Behaviour:

Attribute should be translated to the given locale or fallback to Laravel default locale.

### Actual Behaviour:

`translate()` method ignores locale, and returns the first option value saved in database.

### Steps To Reproduce:

In a multi-language store, define a product variant option.
The `name` attribute stores in the `product_option_values` table like this: `{"en":"10 USD","fa":"10 دلاری"}`
Now, if you call the `ProductVariant::getOption()` method, it returns the **first** value (even if the Laravel default locale is `fa`), which is `10 USD` in the above example.

The problem is here: https://github.com/getcandy/getcandy/blob/5020fdb7e296cae954cff4b31eda23b33fbd41cd/packages/core/src/Base/Traits/HasTranslations.php#L29 
`$values` type is `stdClass`, but used as array.

**Comment by alecritson** [comment]
This should be resolved in v2.0-beta11
