### ISSUE TITLE
Pagination is misaligned in table views

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#257]
- GetCandy version: 2.0.beta-11
- Laravel Version: 8.83.6
- PHP Version: 8.0
- Database Driver & Version: Mysql 8

### Expected Behaviour:

Pagination would be aligned

### Actual Behaviour:

Pagination is misaligned

### Steps To Reproduce:

Go to orders view - see attached screen for how it looks:

<img width="876" alt="Screenshot 2022-04-06 at 08 38 42" src="https://user-images.githubusercontent.com/51899/161921402-5387dcad-a321-426b-8b4f-f58892546c75.png">

**Comment by glennjacobs** [comment]
Duplicate of #156 ?

**Comment by alecritson** [comment]
Is this also after running `php artisan getcandy:hub:install` after upgrading?

**Comment by ryanmitchell** [comment]
Ah nice, that did the trick @alecritson thank you!
