### ISSUE TITLE
Quill editor styles lack margin/padding

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#265]
- GetCandy version: 2.0-beta12
- Laravel Version: 8.83.6
- PHP Version: 8.0
- Database Driver & Version: Mysql 8

### Expected Behaviour:

When taking line breaks in a rich text editor there is no spacing between paragraphs/headings/uls etc.

### Actual Behaviour:

There would be line breaks

### Steps To Reproduce:

See screenshot for visual representation and html code. A client would likely add extra line breaks to compensate which would then reflect on the front end as unnecessary paragraphs.

<img width="616" alt="Screenshot 2022-04-13 at 09 16 18" src="https://user-images.githubusercontent.com/51899/163132119-e7299e5e-5078-4e6f-ae73-16ddc7fb5ed0.png">

**Comment by alecritson** [comment]
Thanks for reporting, since it's using the Editor's own theme this might need some custom CSS to sort out 🤔
