### ISSUE TITLE
Uploading from slots

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#277]
As discussed a bit on Discord... 

I have a slot on the product add/edit screen that also supports uploading (of a sample of the book). However the uploader clashes with the image uploader as it also listens for the `upload:finished` livewire event.

We probably need a way in the file upload component of recognising the source that initiated the upload.

**Comment by alecritson** [comment]
Thanks @ryanmitchell this is on the radar and something we'll be addressing asap :)

**Comment by alecritson** [comment]
@ryanmitchell I've started a branch on [feat/fileupload-improvements](https://github.com/getcandy/getcandy/tree/feat/fileupload-improvements) which has a small tweak to the `HasImages` trait. Not sure if this will solve the issue but might be a start?

**Comment by ryanmitchell** [comment]
Great, so does that mean I use the value of the $name param to determine if its come from the slot or not?

**Comment by alecritson** [comment]
It looks like `$name` is going to be the name of the attribute on `wire:model` so I assume you should be able to check that there.

**Comment by ryanmitchell** [comment]
Great. Puts a bit on a responsibility on the slot developer to act responsibly but I guess that’s fine.

**Comment by alecritson** [comment]
One thing I did notice was that the event is only emitted to itself, so if you're component had `WithFileUploads` trait and was doing the upload, it shouldn't propagate to the product component 🤔

**Comment by ryanmitchell** [comment]
I’ll take a look this week and report back

**Comment by alecritson** [comment]
Interesting, i'll take another look 🙄

**Comment by alecritson** [comment]
Weird, it gets removed for me. So the image above is not your custom slot but the main images part of editing a product?

**Comment by ryanmitchell** [comment]
I've done some debugging and its due to the scoping of the `Pond` variable in `Pond = FilePond.create`...

If you change that line to `let Pond = FilePond.create` then it works fine.

**Comment by alecritson** [comment]
Gotcha, I've pushed up a tweak to the branch which hopefully sorts it.

**Comment by ryanmitchell** [comment]
Yep thats what I did - works for me. Thank you.
