### ISSUE TITLE
Product delete cascading

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#285]
GetCandy version: 2.0-beta12
Laravel Version: 8.83.6
PHP Version: 8.0
Database Driver & Version: Mysql 8

### Expected Behaviour:
Deleting a product should delete its variants, prices and urls.

### Actual Behaviour:
The product is deleted (soft-deleted) but this does not cascade down to variants, their prices or urls. This means if you try to add the same SKU or URL again you get an error, even though the variant is 'orphaned'.

### Steps To Reproduce:
Add a product, and give it 2-3 variants.
Delete the product
Add a new product with the same name and use the same skus you used previously
You'll see errors for unique skus and probably URLs to

I appreciate this isnt going to happen a whole lot in the real world, but I'm writing import scripts so coming up against it and though it worth reporting.

**Comment by alecritson** [comment]
Thanks @ryanmitchell it's an interesting point. If you're adding a product again with the same SKU and URL would you not just restore the product that's been soft deleted?

Also, there's the idea of the `published` column against the product so if you wanted to hide it you could set that to 0.

**Comment by ryanmitchell** [comment]
Yeah that’s fine for me. But a client wouldn’t have that option through the admin hub.
