### ISSUE TITLE
Adding attributes after products exist causes errors

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#286]
GetCandy version: 2.0-beta12
Laravel Version: 8.83.6
PHP Version: 8.0
Database Driver & Version: Mysql 8

### Expected Behaviour:
Adding attributes once products/variants should be possible without errors.

### Actual Behaviour:
Adding attributes causes errors in the hub on existing product editing (e.g. GetCandy\FieldTypes\Text::__toString(): Return value must be of type string, null returned).

### Steps To Reproduce:
Create a product
Add a new attribute on variations that is a text or toggle field type
Edit the product
See error.

It can be fixed by updating getValue() in the fieldtypes to check for null but I didn't want to PR that in case you had reasons for not doing it.

**Comment by alecritson** [comment]
Thanks @ryanmitchell , I just tried this and things seemed to work as expected for me. Here's what I did.

1) Added a new text attribute on a product variant
2) Assign it via the product type editing
3) Click on product to edit
4) Click on a variant
5) See the new field

<img width="787" alt="image" src="https://user-images.githubusercontent.com/1488016/168535945-f248ea00-5827-4174-b6dd-4d7beb53211e.png">

**Comment by ryanmitchell** [comment]
When you try to save the product (through code not the UI) do you get the errors? if I PR the changes to the fields required (minimal null checks) are you open to merging anyway?

**Comment by alecritson** [comment]
I must admin I only tried the UI, if there's an error though, happy to see a PR :)
