### ISSUE TITLE
Currency factor failed to resolve when decimal_places = 0

### ISSUE THREAD

**Issue by olragon** [getcandy/getcandy#289]
- GetCandy version: 2.0-beta12
- Laravel Version: 9.11
- PHP Version: 8.1
- Database Driver & Version: Mysql 8.0

### Expected Behaviour:
```
echo $price-> price->formatted; // 100 đ
```

### Actual Behaviour:
```
echo $price->price->formatted; // = 10 đ
```

### Steps To Reproduce:
```
$currencyVnd = Currency::create([
    'code' => 'VND',
    'name' => 'Vietnam Dong',
    'exchange_rate' => 1.0000,
    'decimal_places' => 0, // <-- this will cause error
    'enabled' => 1,
    'default' => 1,
]);

$price = Price::create([
    'price' => 100,
    'compare_price' => 100,
    'currency_id' => $currencyVnd->id,
    'priceable_type' => ProductVariant::class,
    'priceable_id' => 1 // replace with real id
]);
```

**Comment by glennjacobs** [comment]
@alecritson I can see the problem here in that the Price datatype isn't using the unit qty correctly. However, I'm not sure what the correct fix is. Could do with chatting this over in the morning.

**Comment by glennjacobs** [comment]
> @alecritson I can see the problem here in that the Price datatype isn't using the unit qty correctly. However, I'm not sure what the correct fix is. Could do with chatting this over in the morning.

Actually, that's completely wrong 😆 Ignore me...
