### ISSUE TITLE
Migration Failed

### ISSUE THREAD

**Issue by marlboro** [getcandy/getcandy#290]
Migration is failing on a newly created database.

- GetCandy version: 2.0-beta12
- Laravel Version: 8.83.13
- PHP Version: 8.1.6
- Database Driver & Version: Sql Server 5.1

### Expected Behaviour:
Successful Migration

### Actual Behaviour:
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (21.97ms)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (10.37ms)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (38.06ms)
Migrating: 2019_12_14_000001_create_personal_access_tokens_table
Migrated:  2019_12_14_000001_create_personal_access_tokens_table (15.15ms)
Migrating: 2021_07_29_100000_create_channels_table
Migrated:  2021_07_29_100000_create_channels_table (14.17ms)
Migrating: 2021_07_29_100001_create_languages_table
Migrated:  2021_07_29_100001_create_languages_table (14.01ms)
Migrating: 2021_07_29_100002_create_channelables_table
Migrated:  2021_07_29_100002_create_channelables_table (40.21ms)
Migrating: 2021_07_29_100003_create_currencies_table
Migrated:  2021_07_29_100003_create_currencies_table (29.69ms)
Migrating: 2021_07_29_100004_create_attribute_groups_table
Migrated:  2021_07_29_100004_create_attribute_groups_table (17.17ms)
Migrating: 2021_07_29_100005_create_attributes_table
Migrated:  2021_07_29_100005_create_attributes_table (23.74ms)
Migrating: 2021_07_29_100006_create_attributables_table
Migrated:  2021_07_29_100006_create_attributables_table (27.63ms)
Migrating: 2021_07_29_100010_create_product_types_table
Migrated:  2021_07_29_100010_create_product_types_table (9.01ms)
Migrating: 2021_07_29_100011_create_tax_classes_table
Migrated:  2021_07_29_100011_create_tax_classes_table (8.43ms)
Migrating: 2021_07_29_100012_create_tax_zones_table
Migrated:  2021_07_29_100012_create_tax_zones_table (16.30ms)
Migrating: 2021_07_29_100020_create_products_table
Migrated:  2021_07_29_100020_create_products_table (17.76ms)
Migrating: 2021_07_29_100025_create_product_associations_table
Migrated:  2021_07_29_100025_create_product_associations_table (20.60ms)
Migrating: 2021_07_29_100030_create_product_variants_table
Migrated:  2021_07_29_100030_create_product_variants_table (60.74ms)
Migrating: 2021_07_29_100040_create_customer_groups_table
Migrated:  2021_07_29_100040_create_customer_groups_table (21.29ms)
Migrating: 2021_07_29_100041_create_customer_group_product_table
Migrated:  2021_07_29_100041_create_customer_group_product_table (30.33ms)
Migrating: 2021_07_29_100041_create_customers_table
Migrated:  2021_07_29_100041_create_customers_table (10.96ms)
Migrating: 2021_07_29_100042_create_customer_customer_group_table
Migrated:  2021_07_29_100042_create_customer_customer_group_table (15.16ms)
Migrating: 2021_07_29_100042_create_customer_user_table
Migrated:  2021_07_29_100042_create_customer_user_table (30.84ms)
Migrating: 2021_07_29_100050_create_prices_table
Migrated:  2021_07_29_100050_create_prices_table (23.26ms)
Migrating: 2021_07_30_100000_create_countries_table
Migrated:  2021_07_30_100000_create_countries_table (21.28ms)
Migrating: 2021_07_30_100001_create_states_table
Migrated:  2021_07_30_100001_create_states_table (11.83ms)
Migrating: 2021_07_30_100002_create_addresses_table
Migrated:  2021_07_30_100002_create_addresses_table (26.30ms)
Migrating: 2021_07_30_100003_create_tax_zone_countries_table
Migrated:  2021_07_30_100003_create_tax_zone_countries_table (16.22ms)
Migrating: 2021_07_30_100004_create_tax_zone_states_table
Migrated:  2021_07_30_100004_create_tax_zone_states_table (16.82ms)
Migrating: 2021_07_30_100005_create_tax_zone_postcodes_table
Migrated:  2021_07_30_100005_create_tax_zone_postcodes_table (18.99ms)
Migrating: 2021_07_30_100006_create_tax_zone_customer_groups_table
Migrated:  2021_07_30_100006_create_tax_zone_customer_groups_table (14.75ms)
Migrating: 2021_07_30_100007_create_tax_rates_table
Migrated:  2021_07_30_100007_create_tax_rates_table (14.42ms)
Migrating: 2021_07_30_100008_create_tax_rate_amounts_table
Migrated:  2021_07_30_100008_create_tax_rate_amounts_table (24.09ms)
Migrating: 2021_08_10_101547_create_media_table
Migrated:  2021_08_10_101547_create_media_table (19.61ms)
Migrating: 2021_08_10_102000_create_collection_groups_table
Migrated:  2021_08_10_102000_create_collection_groups_table (10.86ms)
Migrating: 2021_08_10_103000_create_collections_table
Migrated:  2021_08_10_103000_create_collections_table (25.01ms)
Migrating: 2021_08_10_103001_create_collection_product_table
Migrated:  2021_08_10_103001_create_collection_product_table (17.01ms)
Migrating: 2021_08_10_103002_create_collection_customer_group_table
Migrated:  2021_08_10_103002_create_collection_customer_group_table (33.88ms)
Migrating: 2021_08_17_142630_create_activity_log_table
Migrated:  2021_08_17_142630_create_activity_log_table (19.91ms)
Migrating: 2021_08_19_110000_create_staff_table
Migrated:  2021_08_19_110000_create_staff_table (25.31ms)
Migrating: 2021_08_19_113700_create_staff_permissions_table
Migrated:  2021_08_19_113700_create_staff_permissions_table (13.72ms)
Migrating: 2021_09_09_100000_create_product_options_table
Migrated:  2021_09_09_100000_create_product_options_table (8.14ms)
Migrating: 2021_09_09_100001_create_product_option_values_table
Migrated:  2021_09_09_100001_create_product_option_values_table (11.02ms)
Migrating: 2021_09_09_100010_create_product_option_value_product_variant_table
Migrated:  2021_09_09_100010_create_product_option_value_product_variant_table (15.64ms)
Migrating: 2021_09_10_100000_create_tags_table
Migrated:  2021_09_10_100000_create_tags_table (10.05ms)
Migrating: 2021_09_10_100001_create_taggables_table
Migrated:  2021_09_10_100001_create_taggables_table (13.54ms)
Migrating: 2021_09_29_100000_create_urls_table
Migrated:  2021_09_29_100000_create_urls_table (27.57ms)
Migrating: 2021_10_01_090000_create_orders_table
Migrated:  2021_10_01_090000_create_orders_table (42.65ms)
Migrating: 2021_10_01_090001_create_order_lines_table
Migrated:  2021_10_01_090001_create_order_lines_table (38.06ms)
Migrating: 2021_10_01_090002_create_order_addresses_table
Migrated:  2021_10_01_090002_create_order_addresses_table (32.07ms)
Migrating: 2021_10_01_090003_create_transactions_table
Migrated:  2021_10_01_090003_create_transactions_table (28.32ms)
Migrating: 2021_10_01_100000_create_carts_table
Migrated:  2021_10_01_100000_create_carts_table (31.83ms)
Migrating: 2021_10_01_100001_create_cart_addresses_table
Migrated:  2021_10_01_100001_create_cart_addresses_table (24.51ms)
Migrating: 2021_10_01_100001_create_cart_lines_table
Migrated:  2021_10_01_100001_create_cart_lines_table (14.97ms)
Migrating: 2021_10_02_100000_create_saved_carts_table
Migrated:  2021_10_02_100000_create_saved_carts_table (18.76ms)
Migrating: 2022_01_12_100000_add_columns_to_attributes_table
Migrated:  2022_01_12_100000_add_columns_to_attributes_table (21.68ms)
Migrating: 2022_01_12_100001_add_attribute_data_to_product_variants_table
Migrated:  2022_01_12_100001_add_attribute_data_to_product_variants_table (7.11ms)
Migrating: 2022_01_12_100002_add_default_column_to_tax_classes_table
Migrated:  2022_01_12_100002_add_default_column_to_tax_classes_table (9.49ms)
Migrating: 2022_01_18_100000_add_starts_ends_at_to_channelables_table
Migrated:  2022_01_18_100000_add_starts_ends_at_to_channelables_table (469.00ms)
Migrating: 2022_01_18_100001_add_customer_id_to_orders_table
Migrated:  2022_01_18_100001_add_customer_id_to_orders_table (9.43ms)
Migrating: 2022_02_25_100000_create_saved_searches_table
Migrated:  2022_02_25_100000_create_saved_searches_table (14.31ms)
Migrating: 2022_03_11_100000_remove_formatting_columns_from_currencies_table
Migrated:  2022_03_11_100000_remove_formatting_columns_from_currencies_table (28.96ms)
Migrating: 2022_03_17_100000_add_fields_to_transactions_table

   Illuminate\Database\QueryException

  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The index 'transactions_refund_index' is dependent on column 'refund'. (SQL: DECLARE @sql NVARCHAR(MAX) = '';SELECT @sql += 'ALTER TABLE [dbo].[transactions] DROP CONSTRAINT ' + OBJECT_NAME([default_object_id]) + ';' FROM sys.columns WHERE [object_id] = OBJECT_ID('[dbo].[transactions]') AND [name] in ('refund') AND [default_object_id] <> 0;EXEC(@sql);alter table "transactions" drop column "refund")

  at C:\Web\www\getcandy\vendor\laravel\framework\src\Illuminate\Database\Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

  1   C:\Web\www\getcandy\vendor\laravel\framework\src\Illuminate\Database\Connection.php:501
      PDOException::("SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The index 'transactions_refund_index' is dependent on column 'refund'.")

  2   C:\Web\www\getcandy\vendor\laravel\framework\src\Illuminate\Database\Connection.php:501
      PDOStatement::execute()

### Steps To Reproduce:
php artisan migrate

**Comment by glennjacobs** [comment]
I'm sorry, but GetCandy does not support MS Sql Server. Please see requirements here https://docs.getcandy.io/installation.html#requirements

**Comment by marlboro** [comment]
Ok, fair enough, but then your claim to be Laravel E-Commerce is literally a half truth.  Maybe put an asterisk on the website since you only support half of the databases supported by Laravel.

**Comment by glennjacobs** [comment]
Maybe submit a PR to help us support it?

**Comment by glennjacobs** [comment]
I've added MSSQL support to the roadmap and it's open to contributions.
