### ISSUE TITLE
placed_at null can't be formatted to date

### ISSUE THREAD

**Issue by Thomasmuur** [getcandy/getcandy#301]
- GetCandy version: dev-main
- Laravel Version: 8.75
- PHP Version: 8.0.16
- Database Driver & Version: MySQL 8.0.28

### Expected Behaviour:
It should open an order in the hub.

### Actual Behaviour:
It gives an error
![image](https://user-images.githubusercontent.com/20844820/170580079-66bb608e-a482-4a3b-90d5-3d63a15b37fd.png)
![image](https://user-images.githubusercontent.com/20844820/170580088-174a427a-772f-45ce-8210-c1b968d1f1b6.png)

### Steps To Reproduce:
Open an order in the hub where the placed_at is NULL, so probably not paid or anything.

**Comment by glennjacobs** [comment]
Ryan advised this may be related to orders not having a transaction. We need to investigate.

**Comment by glennjacobs** [comment]
I agree, I think we need to do some testing around these different scenarios.
