### ISSUE TITLE
CartLineModifiers and CartModifiers only work on the first pipeline registered

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#304]
### Expected Behaviour:
That you can register multiple cart line and cart modifiers and they would all process.

### Actual Behaviour:
Only the first one you register processes.

### Steps To Reproduce:
Make 2 simple cart line modifiers:

```
class ModifierOne extends CartLineModifier
{
    public function calculating(CartLine $cartLine)
    {
        echo 1;
    }
}
```

```
class ModifierTwo extends CartLineModifier
{
    public function calculating(CartLine $cartLine)
    {
        echo 2;
    }
}
```

and register them:

        $cartLineModifiers->add(
           ModifierOne::class,
        );
                
        $cartLineModifiers->add(
           ModifierTwo::class
        );

Add something to your cart and you'll see only modifier one echoes a response.

Looking at [this article](https://jeffochoa.me/understanding-laravel-pipelines), it seems its due to you not calling the $next closure in the modifiers.

**Comment by alecritson** [comment]
Hi @ryanmitchell I've put together a draft PR after looking at this, would be good to get your thoughts https://github.com/getcandy/getcandy/pull/310

**Comment by ryanmitchell** [comment]
Yeah I think that should do it.

**Comment by ryanmitchell** [comment]
Maybe its worth making it a `final` method so it cant be changed?
