### ISSUE TITLE
Add a menu item after another menu item isn’t working for me

### ISSUE THREAD

**Issue by snad1** [getcandy/getcandy#317]
- GetCandy version: 2.0-beta13.1
- Laravel Version: 9.11
- PHP Version: 8.1.5
- Database Driver & Version: Mysql 5.7.28

### Expected Behaviour:
Add menu item after specified menu item 

```
$slot = Menu::slot('sidebar');

$slot->addItem(function ($item) {
    $item
          ->name('Merchants')
          ->handle('hub.merchants.index')
          ->route('hub.merchants.index')
          ->icon('identification');
},'hub.products');
```

### Actual Behaviour:
All menu items added, start from the beginning  ie comes at the top of the Dashboard menu item

<img width="245" alt="Screenshot 2022-06-13 at 12 03 57" src="https://user-images.githubusercontent.com/29527925/173417026-db7ccb36-aa7b-47e8-8b91-0e419d3b649f.png">

### Steps To Reproduce:

` class AppServiceProvider extends ServiceProvider{
     
    public function register()
    {
        $this->bootHub();
    }

    public function boot()
    {
        //
    }

    private function bootHub()
    {

        $this->registerLivewireComponents();

        $slot = Menu::slot('sidebar');

        $slot->addItem(function ($item) {
            $item
                ->name('Merchants')
                ->handle('hub.merchants.index')
                ->route('hub.merchants.index')
                ->icon('identification');
            },'hub.products')
            ->addItem(function ($item) {
            $item
                ->name('Merchant Forms')
                ->handle('hub.merchants.reviews')
                ->route('hub.merchants.reviews')
                ->icon('identification');
        });
    }

    private function registerLivewireComponents()
    {
        Livewire::component('hub.components.merchants.index', Index::class);
        Livewire::component('hub.components.merchants.create', Create::class);
        Livewire::component('hub.components.merchants.edit', Edit::class);
        Livewire::component('hub.components.merchants.review', FormReview::class);
    }

} `

**Comment by alecritson** [comment]
Hi @snad1 

Using the example above I can't seem to reproduce this. Can you provide more code? i.e. where you are calling this method etc.

**Comment by snad1** [comment]
@alecritson  

It issue has been updated

**Comment by alecritson** [comment]
You need to put `$this->bootHub();` inside the `boot` method on the service provider. and then pass through the merchant index handle to the `addItem` method:

```php
$slot->addItem(function ($item) {
    $item
        ->name('Merchants')
        ->handle('hub.merchants.index')
        ->route('hub.merchants.index')
        ->icon('identification');
}, 'hub.products')->addItem(function ($item) {
    $item
        ->name('Merchant Forms')
        ->handle('hub.merchants.reviews')
        ->route('hub.merchants.reviews')
        ->icon('identification');
}, 'hub.merchants.index');
```

**Comment by snad1** [comment]
Alright thanks this works
