### ISSUE TITLE
Showing variant slots when there is only 1 variant

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#318]
This may end up being more a question rather than an issue, but interested to hear your thoughts.

I have a slot for variants (downloadable files), which works fine when there are multiple variants, but when a product only has 1 it doesnt get shown as I'm registering it against the variant show slot.

Do we need to update the product views to also show variant slots in this case? Should we give the dev the option of always linking through to the variant show view? Or whats your opinion on what should happen? I could manually add another slot that links through to the variant view as a workaround, but it feels like something that should be considered a bit.

**Comment by alecritson** [comment]
🤔 Interesting point. We have some logic in the templates when there is only 1 variant, so maybe if we only have 1 we can show the variant slots too? I think we do that for attributes.

**Comment by ryanmitchell** [comment]
Yeah thats fine, if youre happy with that approach then I can work on a PR
