### ISSUE TITLE
Can't insert videos in description

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#335]
### Expected Behaviour:

That the Rich Text field would allow for videos or video urls to be added so they can be embedded in content.

### Actual Behaviour:

Its not possible to add videos.

### Steps To Reproduce:

Should hopefully be self-evident :)

**Comment by alecritson** [comment]
I think my hesitation is historically when content editors are given free rein with this kind of thing, it can become a bit of a mess. The options currently enabled are to provide formatting for just text. With regards to flowing around content, this could likely be solved with CSS I'd imagine if needed.

You're correct with it just supporting YouTube at the moment, it might be a case of that fieldtype getting enhanced to a "video" fieldtype that can support a range of sources.

I'd be interested to know your thoughts @glennjacobs

**Comment by glennjacobs** [comment]
@alecritson what editor are we using? Does it even support embedding?

**Comment by alecritson** [comment]
We're using https://quilljs.com/ and yeah it does support it, not sure what we'd need to do in the hub to get it working thought.

**Comment by glennjacobs** [comment]
it should probably be configurable, so that devs can choose what options they want. maybe it could be done in the config?

**Comment by alecritson** [comment]
Sure, but we'd still need to add something to be able to upload the files etc

**Comment by glennjacobs** [comment]
It doesn't upload, it uses Base64 encoding, so it just works.
