### ISSUE TITLE
GetAdmin create product route not found

### ISSUE THREAD

**Issue by folkevil** [getcandy/getcandy#337]
- GetCandy version:latest
- Laravel Version: 9.19
- PHP Version: 8.0
- Database Driver & Version: Mariadb 10

### Expected Behaviour:
Create new product in GetAdmin panel, filled all required fields

### Actual Behaviour:
Click Save Product button and it return 404 modal

### Steps To Reproduce:
Use new Laravel installation, install getadmin, then create product, input missing some field then press Save Product

**Comment by alecritson** [comment]
Hi @folkevil is there anything in the laravel log files to indicate what the issue might be?

**Comment by alecritson** [comment]
Hi @folkevil I've not been able to reproduce this and haven't heard anything back so I'll assume this is resolved. If it's still an issue please re open with some more details and we can take a look.
