### ISSUE TITLE
Adding extra images to Product does not seem to work

### ISSUE THREAD

**Issue by gavinhewitt** [getcandy/getcandy#338]
- GetCandy version:latest
- Laravel Version: 9.19
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Expected Behaviour:
There should be extra images after upload.

### Actual Behaviour:
After upload & save it looks as if the image is saved (it's in the list), but if you refresh the page it's gone. There's nothing in the DB either.

### Steps To Reproduce:
Go to a product edit page and upload new images.

**Comment by alecritson** [comment]
@gavinhewitt I've tested this on the demo store and seems to work okay, assuming you're on the demo store too can you try the same on the "Nike Air Huarache" product. I think this might be related to #339 🤔
