### ISSUE TITLE
Saving a variant does not update the record but returns a validation error

### ISSUE THREAD

**Issue by gavinhewitt** [getcandy/getcandy#339]
- GetCandy version: latest
- Laravel Version: 9.16
- PHP Version: 8
- Database Driver & Version: MySQL 8

### Expected Behaviour:
Saving updates the current record with (edited) data.

### Actual Behaviour:
Saving triggers a validation error 'The sku has already been taken'.

### Steps To Reproduce:
Click save on a product variant

**Comment by alecritson** [comment]
Thanks for reporting @gavinhewitt , I assume this was on the demo store and using the seeded data?

**Comment by gavinhewitt** [comment]
> Thanks for reporting @gavinhewitt , I assume this was on the demo store and using the seeded data?

Yes, it was. Is it a known issue?

**Comment by alecritson** [comment]
It was an issue on the demo store where the seeder was duplicating an SKU for a different product, leading to this result. You can grab the latest changes from the demo store and re-seed which should hopefully solve the issue.

I'll close this issue since it's not a fault of GetCandy
