### ISSUE TITLE
Macros with the same name defined on separate models affect eachother

### ISSUE THREAD

**Issue by gavinhewitt** [getcandy/getcandy#346]
- GetCandy version: latest
- Laravel Version: 9.16
- PHP Version: 8
- Database Driver & Version: MySQL 8

### Expected Behaviour:
Macros with the same name but on different models should not affect eachother. 

### Actual Behaviour:
Macros with the same name defined on different models overwrite the previous model. 

### Steps To Reproduce:
```
Product::macro('getPermalink', function () {
            return route('product.show', $this->defaultUrl->slug);
        });
        
        Collection::macro('getPermalink', function () {
            return route('collection.show', $this->defaultUrl->slug);
        });
        ```

**Comment by alecritson** [comment]
@gavinhewitt I've started a draft PR on this issue, with a basic test from what you provided. As you can see on the PR the tests seem to pass. Not sure if there's anything on the test that's different to what you've done?

**Comment by gavinhewitt** [comment]
The slug is correct. It's the rest of the url that's incorrect. Sorry, should have added this info in the issue 😅 

```php
Product::macro('getPermalink', function () {
	return $this->defaultUrl->slug;
});

Collection::macro('getPermalink', function () {
	return $this->defaultUrl->slug;
});


// Routes
Route::get('/product/{slug}', ProductShow::class)->name('product.show');
Route::get('/collection/{slug}', CollectionShow::class)->name('collection.show');

// Behaviour
$collection->getPermalink()
// expected: /collection/foo-slug
// actual: /collection/foo-slug

$product->getPermalink()
// expected: /product/foo-slug
// actual: /collection/foo-slug <----!!!! This
```

**Comment by glennjacobs** [comment]
GetCandy provides the slug, it doesn't provide the prefix of "/collection/" etc. Your code example doesn't explain how that happens.

**Comment by gavinhewitt** [comment]
Sorry, I see I made a mistike in the macro (I copied @alecritson 's bit. The definition in my code is

```php
Product::macro('getPermalink', function () {
            return route('product.show', $this->defaultUrl->slug);
        });
        
        Collection::macro('getPermalink', function () {
            return route('collection.show', $this->defaultUrl->slug);
        });
```

**Comment by alecritson** [comment]
@glennjacobs @gavinhewitt Managed to reproduce and I've updated the PR accordingly.
