### ISSUE TITLE
Changing Product Type on product edit/creation causes an alpinejs issue

### ISSUE THREAD

**Issue by alecritson** [getcandy/getcandy#4]
We're aware of a problem when trying to change between product types, causing an Alpinejs console error to occur.

This is being looked at as we try and upgrade to a later version of Alpine.

**Comment by poppabear8883** [comment]
Just to add to this. Once this error happens, it also breaks the `Description` field. As you type in the description field it spits out the following errors on every keypress event:

![image](https://user-images.githubusercontent.com/7263458/147587994-6e5d1ee2-3782-484f-a877-adb25a8f0dd0.png)

**Comment by alecritson** [comment]
We've just pushed out `2.0-beta5` for the admin hub which should address this issue.

This release comes with a few changes, but the most impactful is that we've moved to a monorepo on this repository and the dependency you use has changed.

To get this update you simply need to make a change in your composer file.

From 

```js
"getcandy/getcandy": "^2.0"
```

To

```js
"getcandy/admin": "^2.0"
```

And then run `composer update`. In the event that packagist hasn't indexed the update core you may need to run this with the `--with-dependencies` argument.

Once updated, if you still find this issue persists, feel free to re open and we can take a look :)
