### ISSUE TITLE
ErrorException occurs when Alpinejs shorthand syntax has Blade directive of the same name. 

### ISSUE THREAD

**Issue by daikazu** [getcandy/getcandy#41]
I'm using the [`wireui/wireui`](https://github.com/wireui/wireui) package and it contains a custom blade directive called `notify`

```php
 Blade::directive('notify', fn (string $expression) => WireUiDirectives::notify($expression));
```

This causes an exception error in `vendor/getcandy/admin/resources/views/components/notification.blade.php` because blade is trying to parse the alpinejs shorthand syntax `@notify..` as if it was a blade directive.

I would recommend using the full alpinejs syntax as shown below.

```php

// Before
@notify.window="let message = $event.detail.message; level = $event.detail.level; messages.push(message); setTimeout(() => { remove(message) }, 2500)"


//after
x-on:notify.window="let message = $event.detail.message; level = $event.detail.level; messages.push(message); setTimeout(() => { remove(message) }, 2500)"

```

I created a pull request that addresses this issue: #42

**Comment by alecritson** [comment]
Thanks for the contribution, this should now be fixed on 2.0-beta6 of the admin-hub. You can find the guide for upgrading here: https://docs.getcandy.io/upgrading.html

If the issue persists, feel free to reopen :)
