### ISSUE TITLE
collection page bug

### ISSUE THREAD

**Issue by wychoong** [getcandy/getcandy#425]
- GetCandy version: 2.0-beta13.2
- Laravel Version: 9.21.6
- PHP Version: 8.1.5
- Database Driver & Version: 10.6.5-MariaDB

### Expected Behaviour:
- add collection into group

### Actual Behaviour:
1. not showing new collection
2. show collections from other group

### Steps To Reproduce:
1. create new empty collection group
2. add collection to group (behaviour 1)
3. refresh and see the newly added collection
4. add another collection
5. other collection appear (behaviour 2)

https://user-images.githubusercontent.com/67364036/181201113-02168227-894f-4c23-9041-e93d39828163.mov

**Comment by alecritson** [comment]
Thanks for reporting @wychoong will take a look and try reproduce

**Comment by wychoong** [comment]
> Thanks for reporting @wychoong will take a look and try reproduce

an additional request, would it be ok to "open" the new collection group upon create?
