### ISSUE TITLE
GC Generator Commands

### ISSUE THREAD

**Issue by adam-code-labx** [getcandy/getcandy#478]
**Is your feature request related to a problem? Please describe.**
Current problem is there is a lot of work involved to create new sections for the hub, I believe internally my suggested commands will speed up your development workflow.

**Describe the solution you'd like**
The solution I have come up with is a set of artisan commands with custom stubs to quickly generate new sections for the hub.
I would like to make another command to generate settings using spatie laravel settings package integrated without filament forms, so we can use the existing form components.

**Describe alternatives you've considered**
Potentially this could be a package if you feel this does not belong in the hub?

**Additional context**
Currently this is based on the new refactor suggestions, however I do plan to create a legacy stubs directory and update the replacements to support the current hub sections.

Before I create a PR @alecritson @glennjacobs  if you can take a quick look when you have time at the commands and stubs setup.
https://github.com/adam-code-labx/getcandy/tree/feature/gc-generator-commands/packages/admin/src/Console/Commands

If you feel this will be useful going forward I will put a PR together for the current codebase without my suggested refactor changes. Note for the forms as we are not going to be using filament I would suggest the new GetCandyForm abstract class where we can then populate the existing components with our own simple class based form builder. (Compromise 👍)

You can also see the files generated for ShoppingCarts in my last commit here
https://github.com/adam-code-labx/getcandy/commit/34cd3dfd0ab7cd9011957a24c6ddb95482bc75cf

This is the output from the command:

<img width="817" alt="Screenshot 2022-08-15 at 15 28 33" src="https://user-images.githubusercontent.com/53559175/184656196-21314065-5e86-4fc2-a5a4-910226b51ae0.png">

Look forward to hearing your feedback on this one 😃

**Comment by alecritson** [comment]
@adam-code-labx so, to be clear does this command generate files into the core? Or is this to create an add-on boilerplate?

**Comment by adam-code-labx** [comment]
Currently yes to speed up core development.
@alecritson if you like this idea I will update the stubs to support the current codebase.

At a later date, this certainly could be extracted as an add-on providing users with a way to extend GC without having to create PR's to the current codebase.

**Comment by alecritson** [comment]
@adam-code-labx I don't think we need/want the commands to generate code to the core. I think something that auto generates code should be to make add-on boilerplate. I don't think this is solving an issue for the core team or core contributors, we'd be better of encouraging speed for add-on devs.

**Comment by adam-code-labx** [comment]
Ok I will use on my side for now, then look into creating an add-on for users to extend GC later.
