### ISSUE TITLE
Route name matching in SetStaffAuthMiddlewareListener is incorrect

### ISSUE THREAD

**Issue by armezit** [getcandy/getcandy#479]
- GetCandy version: 2.0-beta15
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version:

### Expected Behaviour:
The `\GetCandy\Hub\Listeners\SetStaffAuthMiddlewareListener` should compare the matched route name against various conditions in `handle()` method.

### Actual Behaviour:
It gets route names by name property which obviously returns null and all those conditions always evaluate to false:

https://github.com/getcandy/getcandy/blob/532623b4aa10a17dedf2851fb7c6d8137138d6cc/packages/admin/src/Listeners/SetStaffAuthMiddlewareListener.php#L19-L22

Instead, `getName()` method must be used on Route instance.

There is a commit in git history ca07cb94 which has changed getName() method to name property.
I can't understand the reason behind that change. So @alecritson would you please take a look at the issue?

**Comment by alecritson** [comment]
@armezit Work has been done on this and sorted by @adam-code-labx (🙏 ) so in the next release this should be resolved.
