### ISSUE TITLE
Extending icons

### ISSUE THREAD

**Issue by wychoong** [getcandy/getcandy#486]
**Is your feature request related to a problem? Please describe.**
Currently the icons provided is limited and can be difficult to look for the icon. As of now only 1 place in Hub is using icon which is Side menu registration, which can pass in the icon name or direct pass in SVG. However this is not intuitive and mostly will be already using other icon package in frontend store, eg: [Blade Icons](https://blade-ui-kit.com/blade-icons).

**Describe the solution you'd like**
Extend `GetCandyHub::icon` to use Blade Icons when icon is not available and not <SVG>

**Additional context**
There are concerns of Blade Icons may not be performant but it can be cached or use directive/helper instead of blade component, and caching is not available in GC's icon helper

**Comment by markmead** [comment]
The issue I have with this (and it's not a big one) is developers could start adding icons in any style to GetCandy which runs the risk of it looking like some hacked-together platform. Obviously, that's the developer's version of GetCandy, but impressions do count.

It's worth noting that Heroicons has an update coming soon that will expand its offering.

**Comment by wychoong** [comment]
> could start adding icons in any style

currently this already possible in Side menu registration where you can pass `<svg>` directly. Extending `GetCandyHub::icon` to accept icon name provided by blade-icon only making it more easier and extendable 

so instead of `MenuLink::icon("<svg ..")`, it can be `MenuLink::icon("heroicon-s-heart")` or else we have to do it this way `MenuLink::icon(svg('heroicon-s-heart')->toHtml())`


> It's worth noting that Heroicons has an update coming soon that will expand its offering.

will GC change to use it instead of supplying own `resources/icons`?

**Comment by markmead** [comment]
I think once the update is out for Heroicons it's worth looking into moving all their icons into GetCandy. I doubt they'll cover all needs, but in most cases of GetCandy, an icon is supporting the text and not the solo description of an area.

I quite like the look of Iconic Pro as well, they're quite similar to Heroicons but with a lot more icons. Could be an alternative.

**Comment by wychoong** [comment]
> I think once the update is out for Heroicons it's worth looking into moving all their icons into GetCandy.
> 
v2 dropped Laravel 8 support, so this would be out


will close this as I assume GC won't be adding support to calling `svg` in `GetCandyHub::icon`, so I will be continue using `svg(..)->toHtml()`. 

@markmead  I can submit a PR if open for this idea
