### ISSUE TITLE
Wrong link in settings - tag

### ISSUE THREAD

**Issue by briavers** [getcandy/getcandy#57]
### Expected 
When going to settings -> tags and clicking on edit, i get the screen to edit the tag 

### Actual
You get to edit the language with that ID, 
I could create a PR for this tonight, just let me know if you guys would like that.

![image](https://user-images.githubusercontent.com/26483622/148913650-1d38aae5-c8e6-42f0-91c6-a0633c946387.png)

**Comment by glennjacobs** [comment]
Looks like that somehow got missed. There isn't actually a page to edit the tag yet. If you fancy giving it a go, please do!
