### ISSUE TITLE
Problem if I using UUIDs or GUIDs in my User model

### ISSUE THREAD

**Issue by devmansurov** [getcandy/getcandy#61]
How I can use getcandy if I use UUIDs or GUIDs in my User model?

**Comment by glennjacobs** [comment]
At the moment, you can't. However, you raise a good point and I can't imagine you'd be the only person with this set-up.

We'll take a look and see what can be done.

**Comment by glennjacobs** [comment]
I've created the PR mentioned above. Be good if you could review it and let us know if it fixes the issue for you.

**Comment by devmansurov** [comment]
Add foreign key customization [here](https://github.com/getcandy/core/blob/main/database/migrations/2021_10_01_090000_create_orders_table.php#L14) too

`$table->userForeignKey();`

**Comment by devmansurov** [comment]
You must add `userForeignKey()` everywhere where use `user_id`
