### ISSUE TITLE
Generated attribute handles not compatible in javascript

### ISSUE THREAD

**Issue by itcyborg** [getcandy/getcandy#81]
### Case
Suppose we create an attribute with two or more words for a name, i.e "product warranty" or "short description", then the handle generated will be "product-warranty" or "short-description" respectively.

### Issue
When a product is created that has the attribute above, when retrieving the product and using javascript to render the product attributes, then if the attribute is parsed directly using javascript, then the key for product warranty will be product-warranty which will throw an error.

### Fix
Change the delimiter from '-' to '_'

**Comment by poppabear8883** [comment]
Can you show me an example code snippet of whats not working for you ? This will help with context of the issue.

**Comment by glennjacobs** [comment]
I think this is a reasonable suggestion. I see we have #83 to review.

**Comment by itcyborg** [comment]
Yeah, faced it when I was working on a Vue powered storefront and was a bit challenging to work through it

**Comment by glennjacobs** [comment]
#83 has been merged and solves this.
