### ISSUE TITLE
Login error in Admin hub

### ISSUE THREAD

**Issue by progdog-ru** [getcandy/getcandy#84]
When i try to login - i get error:
```
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The POST method is not supported for this route. Supported methods: GET, HEAD.
http://example.com/hub/login
```

There are no post routes for login

**Comment by alecritson** [comment]
Looks like your app url is set to `http://example.com` so it's trying to post there. Can you double check the `APP_URL` in the env file?

**Comment by progdog-ru** [comment]
no, it's not the url.  look at the file: `packages/admin/routes/web.php` - there is no route for login post request - only get.
Поэтому и есть такая ошибка.

**Comment by progdog-ru** [comment]
example.com I specified for an example.  i changed my url to example.com in the text

**Comment by glennjacobs** [comment]
Sounds like your login form isn't using Livewire for some reason. There isn't an entry in the routes file, because it's a Livewire component.

If you check in your browser console, do you see any errors? Specifically with the page trying to load the Livewire JS?

**Comment by progdog-ru** [comment]
Yes, of course, there is such an error in the console. Thanks!

**Comment by glennjacobs** [comment]
Might be a problem with your web browser set-up. Closing this, as it's not an issue with GetCandy.

**Comment by obchodniuspech** [comment]
I have the same issue, right after the installation. I think, i strictly followed yours instruction on https://docs.getcandy.io/installation.html#requirements . Running on MAMP.

**Comment by glennjacobs** [comment]
> I have the same issue, right after the installation. I think, i strictly followed yours instruction on https://docs.getcandy.io/installation.html#requirements . Running on MAMP.

Check the browser console to see if there's any errors. Likely the Livewire scripts are unable to load for some reason.

**Comment by glennjacobs** [comment]
I think your web server for some reason is not sending those requests to your Laravel app, instead it thinks they're a file because of the `.js` extension.

So you'll need to play with your MAMP config to try make it work properly. Maybe try Nginx if you're using Apache?

**Comment by mouyong** [comment]
![image](https://user-images.githubusercontent.com/10336437/159169115-7b84aad9-8f74-4f6d-a6ef-d693d3b12bef.png)

**Comment by mouyong** [comment]
```
GET http://demostore.hecs.iwnweb.com/livewire/livewire.js?id=940557fc56b15ccb9a2d net::ERR_ABORTED 404 (Not Found)
login?_token=5tt3dfEwjuAkIaAkRjbKCxKN4gbbguKv5Qj6ijNF&email=my24251325%40gmail.com&password=123456:133 Uncaught ReferenceError: Livewire is not defined
    at login?_token=5tt3dfEwjuAkIaAkRjbKCxKN4gbbguKv5Qj6ijNF&email=my24251325%40gmail.com&password=123456:133:27
```

**Comment by dawwwid** [comment]
Sorry it's old but maybe that : https://github.com/lunarphp/lunar/issues/704#issuecomment-1339145124
