### ISSUE TITLE
Unable to fetch products names

### ISSUE THREAD

**Issue by jishadiocod** [getcandy/getcandy#85]
Hi,

I have been added getCandy to my Laravel Project. I can add products. When I fetch the products from my frond end HomeController its not working.

I have set **en** is the default language and both admin and code.

   `public function home(){
        $products = Product::get();
        return view('welcome',compact('products'));
    }`

welcome.blade.php

{!! $item->attribute_data['name']->getValue()[App::currentLocale()] !!}

This is the only way now to get the product name. I feel there is something more easy way to get the product name. Please suggest the way to get the name of product...

**Comment by alecritson** [comment]
You should be able to do:

```php
$item->translateAttribute('name');
```

There's some information about it in the docs https://docs.getcandy.io/getcandy/attributes.html#attributes-2

**Comment by jishadiocod** [comment]
Thanks for the support. It's working....
