### ISSUE TITLE
Docs update: shipping/billing address

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#91]
On: https://docs.getcandy.io/getcandy/carts.html#adding-shipping-billing-address

The shipping address formats are wrong:

```
[
    'line_one' => null,
    'line_two' => null,
    'line_three' => null,
    'city' => null,
    'state' => null,
    'postcode' => null,
    'country' => null,
]
```

should be:

```
[
    'first_name' => null,
    'last_name' => null,
    'line_one' => null,
    'line_two' => null,
    'line_three' => null,
    'city' => null,
    'state' => null,
    'postcode' => null,
    'country_id' => null,
]
```

Also the validation error here: https://github.com/getcandy/getcandy/blob/86d39477af3b4de1feaf9653ff94c912cb4a5625/packages/core/src/Actions/Carts/ValidateCartForOrder.php#L63 

Should really pass the errors back so they can be output?

**Comment by NaincyKumariKnoldus** [comment]
Hey @ryanmitchell I have raised a PR for this. Please review my PR!

**Comment by glennjacobs** [comment]
Thank you @ryanmitchell and @NaincyKumariKnoldus, we'll take a look soon.

**Comment by alecritson** [comment]
Hi @ryanmitchell We imagined that the storefront would have their own validation in place for this. When the exception is thrown it's almost a last line of defence to the address being incomplete.

**Comment by ryanmitchell** [comment]
@alecritson thats grand, and I would be planning on validating there, but is there any harm in passing them back when they are available (`$shippingValidator->errors()`) ?

**Comment by glennjacobs** [comment]
I would say the harm is people may start to use them rather than implementing their own validation, which I would consider a risk. We want to encourage the application developer to implement their own validation.

**Comment by ryanmitchell** [comment]
Thats grand, I'll close this off as its not relevant.
