### ISSUE TITLE
Order Email Notifications

### ISSUE THREAD

**Issue by glennjacobs** [getcandy/getcandy#97]
We wish to add order notifications, specifically for emails. But of course, other channels might be required down the line, such as push notifications, SMS, etc.

This thread is to discuss the requirements.

## Requirements

Orders can have (custom) statuses applied to them, and we want to have email notification templates that you can choose from when updating an order's status. E.g. change the status to "Dispatched" and optionally send a suitable email notification to the customer.

Each status can have multiple templates associated, and templates can be associated with more than one order status.

It should be possible to add custom text to an email notification before sending it.

All notifications should be added to the Activity Log which acts as the history for the order. Ideally, we would somehow keep a copy of the email so it can be viewed at a later date.

**Comment by glennjacobs** [comment]
@joelwmale here's the initial quick dump of ideas. @alecritson might like to contribute to it also.

If you want to start a Draft PR at some point, we can feedback.

**Comment by joelwmale** [comment]
Great thanks @glennjacobs. I'll send a draft PR now.

**Comment by joelwmale** [comment]
Draft PR here: https://github.com/getcandy/getcandy/pull/98
