### ISSUE TITLE
composer update not updating required dependencies ie getcandy/core

### ISSUE THREAD

**Issue by poppabear8883** [getcandy/getcandy#99]
It should be noted that I work in a `Laravel Sail Env` on `Windows 10` using `Windows Subsystem Linux (WSL2)`.

Running the command `sail composer update getcandy/admin` seems to *only* update `getcandy/admin` and not its required dependency tree. This has happened to me twice now and after some discussion in discord it was agreed that an issue should be raised here. Ref: https://discord.com/channels/497326121441034240/497332761049300992/936245140874489976

Running `sail composer update getcandy/admin --with-dependencies` is the work-around to this issue, however the issue needs resolved.

Still undetermined if this issue is directly related to GetCandy or not.

**Comment by glennjacobs** [comment]
We are now using "self.version" for requiring the core package. Which will keep them in sync. 

E.g. if you required `dev-main` for the admin hub, you'd get `dev-main` for the core.
